#!/bin/bash

cd /examples/naca0021
unzip -u naca0021_p3_1c.msh.zip
mkdir ../$1gpu-naca0021
cd ../$1gpu-naca0021
cp ../naca0021-input-set/naca0021_p3_1c.msh .
cp ../naca0021-input-set/p3_warmup.ini .
cp ../naca0021-input-set/3d_naca.ini .

pyfr import naca0021_p3_1c.msh naca0021_p3_1c.pyfrm
if [[ -z "$1" ]]; then
    echo "please provide number of GPUs (1-8 supported)"
    exit 1
elif [[ $1 -gt 8 ]]; then
    echo "Maximum of 8 gpus is supported for naca0021 benchmark"
    exit 1
elif [[ $1 -gt 1 ]]; then 
    echo "Creating partisions"
    pyfr partition $1 naca0021_p3_1c.pyfrm .
fi

if [ $? -eq 0 ]; then
        echo "mesh import succeeded"
        mpiexec --allow-run-as-root -np $1 pyfr run -b hip -p naca0021_p3_1c.pyfrm p3_warmup.ini
        if [ $? -eq 0 ]; then
                echo "warmup succeeded"
                time mpiexec --allow-run-as-root -np $1 pyfr restart -b hip -p naca0021_p3_1c.pyfrm naca_p3_1c_warmup_100.00.pyfrs 3d_naca.ini
        else
                echo "warmup failed"
        fi
else
        echo "mesh import failed"
fi
